### DISCUSSION TITLE
Build Process failure related to GoogleAnalytics.AnonymizeIP config

### DISCUSSION THREAD

**Discussion by Aman-Aalam** [gethinode/hinode#1309] [Help]
Hi Folks,

I am using the Hinode theme to power a developer blog and I have recently started hitting an error, perhaps because of a hugo upgrade:

### stacktrace:
```bash
execute of template failed: template: partials/footer/scripts.html:42:18: 
executing "partials/footer/scripts.html" at <$js.Content>: error calling Content: EXECUTE-AS-TEMPLATE: 
failed to transform "/js/main.bundle.js" (text/javascript): 
template: /js/main.bundle.js:43:67: 
executing "/js/main.bundle.js" at <$pc.AnonymizeIP>: can't evaluate field AnonymizeIP in type privacy.GoogleAnalytics
```

This tells me the build process is not able to resolve the `anonymizeIP` values from config files, and that `js.Content` is failing as well.

Here's the section of my `hugo.toml` which mentions Google Analytics options:

```toml

[privacy]
  [privacy.googleAnalytics]
    disabled = 'false'
    respectDoNotTrack = 'true'
    anonymizeIP = 'true'
    useSessionStorage = 'true'
```

Any idea what I am missing, please?

Hinode version: `v0.22.5`
Hugo version: `hugo v0.134.2+extended darwin/arm64 BuildDate=2024-09-10T10:46:33Z VendorInfo=brew`

**Comment by markdumay** [comment]
Try upgrading your Hinode version. This issue has been fixed in [Hinode v0.23.8](https://github.com/gethinode/hinode/releases/tag/v0.23.8), see  https://github.com/gethinode/hinode/issues/882.

**Comment by Aman-Aalam** [comment]
Thank you, updating it resolved this specific issue, but now when I am on `hinode v0.27.12` and `hugo v0.139.4` I get the following a bunch of errors all related to `$base-url` variable, and a warning:

```bash
WARN  Unsupported module parameter: core

ERROR "hugo_cache/modules/filecache/modules/pkg/mod/github.com
/gethinode/hinode@v0.27.12/assets/scss/common/_variables.scss:8:33": 
Undefined variable: "$base-url".

Error: error copying static files: open ..../public/fonts/fa-solid-900.ttf: permission denied
```
Is this the `baseUrl` defined in `hugo.toml` ?
I have a `_default` and a `production` version of `hugo.toml`, the default one doesn't have `baseUrl` defined.

Here's the structure of my `config` directory:

```bash
config
├── _default
│   ├── hugo.toml
│   ├── languages.toml
│   ├── menus
│   │   └── menus.en.toml
│   └── params.toml
└── production
    └── hugo.toml
```

Along with that's, here's how `[modules]` are defined in `params.toml` that I am also getting the warning about:

```toml
    [modules]
        core = ["bootstrap", "flexsearch", "fontawesome"]
```

Any help on what might be going on here, please?

**Reply by anoduck** [reply]
I don't know why someone else has not responded yet, and more than likely, you have probably tinkered around and found the answer. Since I am rather gifted at procrastination, for prosperity, here is my $0.02.

### baseURL

Yes, your [baseURL](https://gohugo.io/methods/site/baseurl/) should be defined in `/config/_default/hugo.toml` as it is an integral part of the framework. If you haven't set it, it should default to `/`, which would equate to the base directory of your website. If you do not want the Google search API to complain about not being able to find canonical URLs, you should set it and set `canonifyURLs = true`. 

I do not host my site on Netlify or GitHub, so I do not touch anything in `config/production/*`. This might just be my unrefined style of doing things, but it is my understanding this is what the existence of `config/production` is for, deployments and "advanced grown up stuff". 

### modules

I do not know where you got that line from, but yes, that could be the cause of a few of your problems. 

* hugo.toml = defines what modules your site uses.
* params.toml = defines the settings for those modules, and by default those settings are not included. 

Here is the end portion of my `hugo.toml` file. There is little different from it and the default.

```toml
[module]
  [module.hugoVersion]
    extended = true
    min = "0.134.0"
    max = ""
  [[module.mounts]]
    source = "archetypes"
    target = "archetypes"
  [[module.mounts]]
    source = "assets"
    target = "assets"
  [[module.mounts]]
    source = "content"
    target = "content"
  [[module.mounts]]
    source = "i18n"
    target = "i18n"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "static"
    target = "static"
  [[module.mounts]]
    source = "netlify.toml"
    target = "assets/config/netlify.toml"
  [[module.imports]]
    path = "github.com/gethinode/hinode"
  [[module.imports]]
    path = "github.com/gethinode/mod-mermaid"
  [[module.imports]]
    path = "github.com/gethinode/mod-leaflet"
```

Make sure something similar is in your `hugo.toml` file, and as far as your `params.toml` file is concerned, any mention of modules `[[modules.*]]` is excluded from the file by default. Unless you are using a module that requires additional configuration in `params.toml`, you should be fine without any mention of them. The only mention of modules in my `params.toml` is:

```toml
[modules.fontawesome]
    skipMissing = true
```

Which basically allows the site to still build when I attempt to include a font awesome icon that does not exist or is misspelled.
