### DISCUSSION TITLE
Google Analytics Tag not showing on production

### DISCUSSION THREAD

**Discussion by ivanbrunodemorais** [gethinode/hinode#331] [Help] [answered]
I have not been able to get the Google Analytics Tag to show when deploying the site for production, when using both the main Repository and the template. I defined the googleAnalytics in the config, and have been trying to edit analytics.js without success.

**Comment by markdumay** [comment]
Some initial thoughts/questions:
- Hinode recently switched from ‘config.toml’ to ‘hugo.toml’, does this have any impact on your site?
- Which steps of https://gethinode.com/docs/configuration/analytics/ have you followed?
- What is the output when you run ‘npm run build’?

**Reply by ivanbrunodemorais** [reply]
Yes, I had recently updated Hinode (to hugo.toml), and finally ended up starting a new project from the template, but still no Google Tag Manager (there is no google analytics tag in the html files in public folder)
I followed following steps only:
1. git clone https://github.com/gethinode/template.git my-hinode-site && cd my-hinode-site
2. npm install
3. Only added googleAnalytics="G-XXXXXXXX" to hugo.toml
4. Didn't change nothing else
5. npm run build:

> npm run build
> 
> > @gethinode/template@0.8.6 prebuild
> > npm run clean
> 
> 
> > @gethinode/template@0.8.6 clean
> > shx rm -rf public resources
> 
> 
> > @gethinode/template@0.8.6 build
> > hugo --gc --minify
> 
> Start building sites … 
> hugo v0.115.1-857374e69358f788bd31ddc55255c5c8e3dcfd80+extended linux/amd64 BuildDate=2023-07-03T17:28:25Z VendorInfo=gohugoio.

Also recently, I updated to Hugo 115.0, not sure if related.

**Comment by markdumay** [comment, marked as answer]
I followed the exact same steps. I placed the `googleAnalytics = "G-xxxxxxxxxx"` value right **above** `[taxonomies]` in `hugo.toml`. When I look into the generated file `public/en/index.html` I do see the following line as expected:

```html
<script async src="https://www.googletagmanager.com/gtag/js?id=G-xxxxxxxxxx"></script>
```

The beginning of the `hugo.toml` file looks like this (I only inserted the Google tag):

```toml
title = "Hinode"
copyright = "Copyright © 2023 Mark Dumay."
paginate = 9
enableGitInfo = true

# additional settings
baseURL = "https://template.gethinode.com/"
canonifyURLs = false
enableEmoji = true
enableRobotsTXT = true
enableInlineShortcodes = true

# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

timeout = "120s"

languageCode = "en-us"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

googleAnalytics = "G-xxxxxxxxxx"

[taxonomies]
  tag = 'tags'
[...]
```
