### DISCUSSION TITLE
How to remove the social media follow section above the footer?

### DISCUSSION THREAD

**Discussion by rohitfarmer** [gethinode/hinode#435] [Help] [answered]
Hi there, thanks for the amazing template. I am new to Hugo, so I am struggling with several things simultaneously. But what is bothering me the most is how I can remove the social media follow section just above the footer from all the pages. At this stage of my website, I do not have a social media account that I want to put there. Any suggestions would be helpful. Thanks!

**Comment by markdumay** [comment, marked as answer]
Glad you like the theme! You can remove the entire social footer by putting an empty file in the following path of your own repo: `layouts/partials/footer/social.html`

I'll also push a change to the Hinode repository and release it in the upcoming version of Hinode. You could then simply disable / remove all social entries in `config/_default/menus/menus.en.toml` (or equivalent file in your configuration).

```toml
# remove or disable the following three default menu entries
[[social]]
  name = "LinkedIn"
  pre = "fab linkedin"
  url = "https://linkedin.com/"
  weight = 10

[[social]]
  name = "GitHub"
  pre = "fab fa-github"
  url = "https://github.com/"
  weight = 20

[[social]]
  name = "Medium"
  pre = "fab medium"
  url = "https://medium.com/"
  weight = 30
```
