### DISCUSSION TITLE
Improve contrast in table-striped

### DISCUSSION THREAD

**Discussion by myrthos** [gethinode/hinode#486] [Ideas]
Personally, I think the contrast difference when using a table with `table-striped` is quite low in dark mode. It is fine in light, but in dark, I need to look really close to actually notice there is a difference. 

Perhaps using the same background colour as a code block could already be an improvement.

**Comment by markdumay** [comment]
Yes, agreed. Let’s add a more contrasting color indeed. 

![image](https://github.com/gethinode/hinode/assets/61946753/115a2b48-3644-4e6b-956a-1564951a7945)

**Comment by markdumay** [comment]
It seems `.table-striped`, `.table-striped-columns`, and `.table-hover` all require adjustment. I'll adjust the stylesheet(s).

**Comment by myrthos** [comment]
I don't know if you consider the current state to be final, but personally I think the contrast difference in dark in the latest version is a bit too much now, whereas in light it is just perfect.

**Comment by markdumay** [comment]
We could tone it down a little. The current contrast ratio is ~7.5, based on `var(--bs-tertiary-color)`. Which color / var would you prefer?

**Comment by myrthos** [comment]
I don't know to be honest. I can experiment with it this weekend and let you know what I prefer. That doesn't mean you have to agree with it obviously :)

**Comment by myrthos** [comment]
I checked it, and changing the color to `var(--bs-tertiary-bg)` looks a lot better.

**Comment by markdumay** [comment]
Thanks, I agree. I fixed the text color of colored/accented tables too. The following code has been pushed to the main repo:

```scss
@if $enable-dark-mode {
    @include color-mode(dark) {
        .table-striped, .table-striped-columns {
            --bs-table-striped-bg: var(--bs-tertiary-bg);
            --bs-table-striped-color: var(--bs-body-color);
        }

        .table-hover {
            --bs-table-hover-bg: var(--bs-tertiary-bg);
            --bs-table-striped-color: var(--bs-body-color);
        }
    }
}
```
