### DISCUSSION TITLE
First level section no longer show content hosted in subdirectories

### DISCUSSION THREAD

**Discussion by dims31** [gethinode/hinode#617] [Help] [answered]
Hello,

I have content organization below and (I think) from hinode 0.21, my top level section (posts) doesn't show content from subdirectories (with _index.md)
If I remove _index.md (from first_topic) content is displayed in top level section but I don't have second level section...
From my homepage featured post are no longer displayed until I force home.sections in param.toml

- content
  - posts
    - first_topic (with _index.md)
        first_post
        second_post
    - second_topic
    ....

**Comment by markdumay** [comment]
Have your tried adding `nested = true` in your `params.toml` file?

```toml
[sections]
    [sections.posts]
        title = "All posts recursively"
        nested = true
```
