### DISCUSSION TITLE
Table shortcode results in “error calling intersect: can't iterate over map”

### DISCUSSION THREAD

**Discussion by ckamps** [gethinode/hinode#708] [Help] [answered]
I attempted to use the example of aligned cells and headers on my site, but the build fails with the failure shown below:

https://gethinode.com/docs/content/tables/#aligned-cells-and-headers

```
…
execute of template failed: template: shortcodes/table.html:2:19: executing "shortcodes/table.html" at <intersect .Params $responsiveVals>: error calling intersect: can't iterate over map[string]interface {}
```
Here’s an excerpt from the failing page. If i remove the example table that uses the shortcode, the build works fine.

<img width="1033" alt="image" src="https://github.com/gethinode/hinode/assets/1332810/83c90847-c8c7-4a39-89df-1d557220a5f5">

I’m running GitHub Actions with steps that look like this:

```
…

      - name: Install Dart Sass Embedded # Installs dart-sass
        run: sudo snap install dart-sass-embedded
      - name: Set up Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: latest
          extended: true
      - name: Build
        run: hugo
      - name: Deploy to S3
        run: hugo deploy --force --maxDeletes -1 --invalidateCDN
```

`params.yaml`

<img width="276" alt="image" src="https://github.com/gethinode/hinode/assets/1332810/0289e928-7f30-4c82-9e68-e0250cad2ef2">

`hugo.yaml`

<img width="429" alt="image" src="https://github.com/gethinode/hinode/assets/1332810/643ebbef-8a63-401a-bfd8-0afcef42b1c2">
