### DISCUSSION TITLE
No site logo when publishing on subdomain

### DISCUSSION THREAD

**Discussion by vinser** [gethinode/hinode#937] [Help] [answered]
In my site config file `config/_default/params.toml` I set site logo as
```toml
[navigation]
    logo = "/img/SV-1-1.svg"
```
and put logo svg in static/img/SV-1-1.svg like it is stated in Hinode docs https://gethinode.com/docs/configuration/navigation/#basic-configuration

And on developer server `hugo server` site logo is in place
![image](https://github.com/gethinode/hinode/assets/14954512/6cd6d704-e061-4886-8760-7ea611d4034a)
but when I publish site on GitHub Pages all goes well except logo
![image](https://github.com/gethinode/hinode/assets/14954512/a6c94463-5dbc-44f1-a246-9d2bfbae87e1)

Is there any idea how to fix logo?

**Comment by markdumay** [comment]
Please double check the folder, it should be in static. From the docs:

> The vector image file is expected to be present in your local static/img folder.

**Reply by vinser** [reply]
Thanks for response.  Sorry about my misled you - my logo image is of of course in folder static/img/SV-1-1.svg 

I was able to simulate the case on a local `hugo server` and I think that the reason is that the search for static resources is done relative to the domain of the baseURL, for example, `baseUrl=https://example.com/`, and not relative to the full baseURL of project site `baseURL=https://example.com/hugo-hinode/`. 

That is what I see in browser developer mode on my local host. Please, look at 404 about my logo `SV-1-1.svg` and inter regular font
`baseURL = 'https://example.com/hugo-hinode'`

![image](https://github.com/gethinode/hinode/assets/14954512/3bb2da7e-7aa6-4d2d-9ec3-be44dd6718a2)

The same we can see on GitHup Pages publication host, `baseURL = 'https://vinser.github.io/hugo-hinode'`

![image](https://github.com/gethinode/hinode/assets/14954512/b7a9895c-bf87-4c20-b8da-c8117de53463)

As they know, Github provides the following structure for publication: 
```
https://<person>.github.io - main personal website 
and project sites
https://<person>.github.io/<project name 1>
https://<person>.github.io/<project name 2>
...
https://<person>.github.io/<project name n>
```
Hence the question is - how to publish the project website on GitHub Pages?

**Reply by markdumay** [reply]
Have you tried the guide from https://gohugo.io/hosting-and-deployment/hosting-on-github/?

They use the following command to adjust the base URL:

```yml
     - name: Build with Hugo
        env:
          # For maximum backward compatibility with Hugo modules
          HUGO_ENVIRONMENT: production
          HUGO_ENV: production
          TZ: America/Los_Angeles
        run: |
          hugo \
            --gc \
            --minify \
            --baseURL "${{ steps.pages.outputs.base_url }}/"          
```
