### DISCUSSION TITLE
Sidebar is not shown for docs

### DISCUSSION THREAD

**Discussion by vinser** [gethinode/hinode#991] [Help] [answered]
Please help me to find what I'm doing wrong

I'm trying to create quite simple `docs` section with 4 pages but get empty sidebar for these pages

In `data` folder I put `docs.en.yaml` file which contains these 4 titles
```
- title: Introduction
- title: How to use
- title: Advanced settings
- title: Using docker
```
In `params.toml`  
```toml
[docs]
  contentPath = "/docs/"

[navigation]
    logo = "/img/VS.svg"
    anchor = true
    color = ""
    fixed = true
    offset = "5.5em"
    search = true
    breadcrumb = false
    toc = true
    sidebar = true
    size = "lg"

[sections]
    [sections.docs]
        title = "Manuals"
        layout = "card"
        sort = "title"
        reverse = false
        nested = false
        background = ""
        color = "body-tertiary"
        style = "border-0 shadow card-feature card-shrink card-body-margin"
        cols = 3
        padding = "3"
        header = "none"
        footer = "none"
        orientation = "stacked"
        homepage = 3
```

**Comment by vinser** [comment]
All docs pages have
```yml
---
layout: docs
---
```
Is there a document site example with multilingual mode?

**Comment by vinser** [comment]
I found out that the problem is that I cannot set the language for the `data` folder containing `docs.ylml`, `releases.yaml`, timeline....
In `hugo.toml` there is a module section which is used to mount English content to `docs` 
```toml
 [[module.mounts]]
    source = "content/en/docs/latest"
    target = "content/docs"
    lang = 'en'
  [[module.mounts]]
    source = "content/en"
    target = "content"
    lang = 'en'
    excludeFiles = 'docs/latest/*'
```
Without these mounts sidebar is not shown

Please give me an advice how it should be configured for two languages 
Without this its impossible to make good multilingual documentation site using the theme

**Comment by markdumay** [comment]
I can confirm the current sidebar does not support multiple languages, rendering its functionality quite useless in multi-languages sites. I've raised a new issue #995 and will release a fix soon. I found another issue #996 that will be fixed as well. I'll update the [docs](https://gethinode.com/docs/configuration/navigation/#sidebar-navigation) too.

**Comment by markdumay** [comment]
I've released [v0.24.4](https://github.com/gethinode/hinode/releases/tag/v0.24.4) that should fix the issues. I've setup a temp demo repository here: https://github.com/markdumay/docs-test. It includes a sidebar menu for the blog section in three languages.

You should not have to change the mount configuration. The docs repo uses mounts to map the `latest` subfolder to a parent folder. However, this is not a strict requirement.

**Reply by vinser** [reply]
@markdumay Many thanks for your kind efforts. It's all right now with multilingual sidebar, but previous fix for baseURL subfolder done in v0.24.0 was lost. Hogo command gives me such errors  
```
ERROR partial [assets/link.html] - Cannot find page: /subfolder/subfolder/en/blog/first-post
ERROR partial [assets/link.html] - Cannot find page: /subfolder/subfolder/en/blog/second-post
ERROR partial [assets/link.html] - Cannot find page: /subfolder/subfolder/en/blog/third-post
ERROR partial [assets/link.html] - Cannot find page: /subfolder/subfolder/nl/blog/eerste-artikel
ERROR partial [assets/link.html] - Cannot find page: /subfolder/subfolder/nl/blog/tweede-artikel
ERROR partial [assets/link.html] - Cannot find page: /subfolder/subfolder/nl/blog/derde-artikel
```
With `baseURL = 'https://example.com/subfolder/'` subfolder is duplicated and with `baseURL = 'https://example.com/'` all is correct

**Comment by vinser** [comment]
Here is `menu.en.toml`
```toml
[[main]]
  name = "About"
  pageRef = "/about/"
  weight = 10

[[main]]
  name = "Blog"
  pageRef = "/blog/"
  weight = 20

[[main]]
  name = "Projects"
  pageRef = "/projects/"
  weight = 30

[[social]]
  name = "GitHub"
  pre = "fab fa-github"
  url = "https://github.com/"
  weight = 20

# toml-docs-start sample-navigation
[[sample]]
  name = "Blog"
  pageRef = "/blog/"
  weight = 10

[[sample]]
  name = "Projects"
  pageRef = "/projects/"
  weight = 20

# toml-docs-end sample-navigation
```

**Comment by vinser** [comment]
Some kinda regression testing we are doing )

**Reply by vinser** [reply]
`languges.toml` is
```toml
# toml-docs-start lang-main
[en]
languageName = "English"
contentDir = "content/en"
weight = 1
# toml-docs-end lang-main
# toml-docs-start lang-param
[en.params.head]
tagline = "A Hugo Theme"
[en.params.social]
title = "Follow me"
caption = "I work on everything coding and tweet developer memes"
[en.params.footer]
# license = "Licensed under Creative Commons (<a href='https://creativecommons.org/licenses/by-nc-sa/4.0/' class='link-secondary' target='_blank' rel='noopener noreferrer'>CC BY-NC-SA 4.0</a>)."
# toml-docs-end lang-param
[en.params.sections.blog]
reference = "More Posts"
[en.params.sections.projects]
reference = "More Projects"

[nl]
languageName = "Nederlands"
contentDir = "content/nl"
weight = 2
[nl.params.head]
tagline = "Een Hugo Thema"
[nl.params.social]
title = "Volg mij"
caption = "Ik doe aan programmeren en tweet memes"
[nl.params.footer]
# license = "Gelicenseerd onder Creative Commons (<a href='https://creativecommons.org/licenses/by-nc-sa/4.0/' class='link-secondary' target='_blank' rel='noopener noreferrer'>CC BY-NC-SA 4.0</a>)."
[nl.params.sections.blog]
reference = "Meer artikelen"
[nl.params.sections.projects]
title = "Projecten"
reference = "Meer projecten"
```
