### ISSUE TITLE
Allow adding aria-label to featured Actions

### ISSUE THREAD

**Issue by Ipstenu** [gethinode/hinode#1106]
## Problem or enhancement idea

I want to have an action link (the ones on the front page) that is ONLY an icon. Like a link to social media. Right now, there's no way to do that without using `title` and that will display on output.

```
actions:
  about:
    url: "/about-us/"
    title: "About Us!"
    weight: 1
  twitter:
    url: "https://twitter.com/example"
    icon: "fab square-x-twitter"
    label: "Follow Example on X/Twitter"
    weight: 2
  facebook:
    url: "https://www.facebook.com/example"
    icon: "fab facebook"
    label: "Follow Example on Facebook"
    weight: 3
```

I want to have the aria-label so I'm more accessible to my users.

## Proposed solution

If you change the line https://github.com/gethinode/hinode/blob/main/layouts/partials/list/featured.html#L43C21-L43C145 to
this:

` {{ partial "assets/button.html" (dict "href" .url "icon" .icon "label" .label "title" .title "outline" .outline "order" "last" "justify" "start") }}`

then you can pass in the label!

## Alternatives

I considered heavily modding CSS to hide the text only on those, but for now I've made a fork of `layout/partials/list/featured.html`

## Additional context

Doing this will allow people to have button-images or icons without sacrificing accessibility.
