### ISSUE TITLE
[BUG] Multi language configuration

### ISSUE THREAD

**Issue by ahalma** [gethinode/hinode#1178]
## Describe the bug

I'm adapting the default hinode template to support multiple langues, but content does not show correctly. It must be a misconfiguration instead of a bug, but could use help to pinpoint it.

## To reproduce

hugo.toml:
```
languageCode = "en-us"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
```

content:
```
content
├── en
│   ├── _index.md
│   └── about.md
└── nl
    ├── _index.md
    └── about.md
```

languages.toml:
```
[en]
languageName = "English"
contentDir = "content/en"
weight = 1
[en.params.head]
tagline = "My Project"
[en.params.social]
title = "Follow me"
caption = "The latest news"
[en.params.footer]
# license = "Licensed under Creative Commons (<a href='https://creativecommons.org/licenses/by-nc-sa/4.0/' class='link-secondary' target='_blank' rel='noopener noreferrer'>CC BY-NC-SA 4.0</a>)."

[nl]
languageName = "Nederlands"
contentDir = "content/nl"
languageCode = "nl"
weight = 2
[nl.params.head]
tagline = "Mijn Project"
[nl.params.social]
title = "Volg me"
caption = "Het laatste nieuws"
[nl.params.footer]
```

When starting the site, the language menu shows, but the content is from both languages.

![CleanShot 2024-09-09 at 08 05 30@2x](https://github.com/user-attachments/assets/eca32ac0-6e5e-4af2-92d5-05a3204b157d)

And the Dutch page shows no content:
![CleanShot 2024-09-09 at 08 10 15@2x](https://github.com/user-attachments/assets/432abeb4-bf8e-4f1c-9372-64a7dfbff99e)

## Expected behavior

Content separated by language.

## Log file

```
                   | EN  | NL   
-------------------+-----+------
  Pages            |  18 |   6  
  Paginator pages  |   0 |   0  
  Non-page files   |   0 |   0  
  Static files     | 104 | 104  
  Processed images |  12 |   0  
  Aliases          |   6 |   0  
  Cleaned          |   0 |   0  

Built in 719 ms
Environment: "development"
Serving pages from disk
Web Server is available at http://localhost:1313/ (bind address 0.0.0.0) 

```
## Host environment

Please complete the following information where applicable.

 - Hinode version:v0.14.0
 - Host OS: macOS Ventura 14.6.1
 - Node version: v22.6.0
 - @gethinode/template@0.14.0
 - hugo v0.134.1

## Hugo environment

Copy the output of `hugo env` or `npm run env` here.

```bash
> @gethinode/template@0.14.0 env
> hugo env

hugo v0.134.1-2f89169baa87a9db47e288b60705f4e99e21a945+extended darwin/arm64 BuildDate=2024-09-05T10:17:50Z VendorInfo=gohugoio
GOOS="darwin"
GOARCH="arm64"
GOVERSION="go1.23.0"
github.com/sass/libsass="3.6.6"
github.com/webmproject/libwebp="v1.3.2"

```

**Comment by ahalma** [comment]
It seems the language paths are nested... 
![CleanShot 2024-09-09 at 13 29 20@2x](https://github.com/user-attachments/assets/28beadc8-b8e2-4451-ab2d-452d37f452cd)

**Comment by markdumay** [comment]
Just by looking at the config, does it help if you delete the following line?

```toml
languageCode = "nl"
```

**Comment by ahalma** [comment]
I removed that line, but the problem remains...
Could it be related to #1134 ?

**Comment by markdumay** [comment]
Does it help if you disable the content mount in `hugo.toml`?

```toml
[module]
  # [[module.mounts]]
  #   source = "content"
  #   target = "content"
```

**Comment by ahalma** [comment]
Yes! That improves the situation substantially!

The proper content is now available when selecting a language. Also the URLs make sense.

The menu items and the footer for the other language don't show, however. 

English (correct):
![CleanShot 2024-09-11 at 09 07 37@2x](https://github.com/user-attachments/assets/4a1294a2-9238-44bf-89ce-164b59d406a6)

Dutch (missing elements):
![CleanShot 2024-09-11 at 09 08 33@2x](https://github.com/user-attachments/assets/688f717a-80f3-4d6d-bb08-2c12eb82a291)

To be sure: I cloned the template and just added to `/content`. I did not provide translations in `/i18n`.

**Comment by markdumay** [comment]
Great! You will need to define the Dutch translations to get the menu and footer working. 

You need to add entries for `[nl]` in `languages.toml`, similar to `[en]`:
```toml
[en]
    [en.params.social]
        title = "Follow me"
        caption = "The latest news"
```

Next you need to create a new file `menus/menu.nl.toml`, using `menus/menu.en.toml` as reference:
```toml
[[main]]
  name = "Home"
  pageRef = "/"
  weight = 10

[[main]]
  name = "Tags"
  pageRef = "/tags"
  weight = 20

[[social]]
  name = "LinkedIn"
  pre = "fab linkedin"
  url = "https://linkedin.com/"
  weight = 10

[[social]]
  name = "GitHub"
  pre = "fab fa-github"
  url = "https://github.com/"
  weight = 20

[[social]]
  name = "Medium"
  pre = "fab medium"
  url = "https://medium.com/"
  weight = 30
```
