### ISSUE TITLE
[BUG] custom 404.html not in root

### ISSUE THREAD

**Issue by d-oit** [gethinode/hinode#1210]
## Describe the bug

any page who not found:
https://demo.gethinode.com/en/gsfgsf

shows the server (netlify) and not the custom 404.html

## Expected behavior

404.html in public folder

## Screenshots

![image](https://github.com/user-attachments/assets/357ece22-a0b3-4a65-923e-e66a987e054b)

## Host environment

Please complete the following information where applicable.

 - Hinode version: 0.26.7

**Comment by d-oit** [comment]
https://github.com/gohugoio/hugo/issues/5161

**Comment by markdumay** [comment]
Thanks for submitting a PR to fix this @d-oit! I've merged the changes with the main branch. 

I've revised the server headers in [v0.27-beta-3](https://github.com/gethinode/hinode/releases/tag/v0.27.0-beta3), so I'll include your remarks here: https://gethinode.com/docs/advanced-settings/server-headers/

**Comment by markdumay** [comment]
BTW, I adjusted the redirects from `**` to `*` to improve compatibility with Netlify:

```toml
[[redirects]]
	from = '/fr/*'
	to = '/fr/404.html'
	status = 404

[[redirects]]
	from = '/nl/*'
	to = '/nl/404.html'
	status = 404

[[redirects]]
	from = '/en/*'
	to = '/en/404.html'
	status = 404

[[redirects]]  # Default language should be last.
	from = '/*'
	to = '/en/404.html'
	status = 404
```
