### ISSUE TITLE
[BUG] Sidebar menu items with custom mappings don't show as active

### ISSUE THREAD

**Issue by timcappalli** [gethinode/hinode#1335]
## Describe the bug

When a link is manually mapped in `docs.yml` with different text than the title, the menu item does not show as active when clicked.

It doesn't seem to be an issue when `link` is just the same text with or without a space (see screenshots).

## To reproduce

1. Add a new docs page
2. Add a new menu/sidebar item using a different name, and add the `link` attribute underneath
3. Click the page in the sidebar

## Expected behavior

The menu item should be `a:active`.

## Log file

n/a

## Screenshots

Here's the relevant docs.yml section:

```yaml
- title: Reference
  pages:
    - title: Android
    - title: "iOS & iPadOS"
      link: iOS
    - title: Chrome OS
      link: chromeos
    - title: macOS
    - title: Windows
    - title: Known Issues
    - title: Specifications
      link: specs
    - title: Terms
```

"Chrome OS" page (working, just has a space)

![image](https://github.com/user-attachments/assets/66c9d770-ef54-40d7-a313-d5b300d7c7dd)

"Windows" page (working, exact match)

![image](https://github.com/user-attachments/assets/aeb98152-e39e-43ac-b365-efd10274ed6b)

"iOS & iPadOS" (not working, different)

![image](https://github.com/user-attachments/assets/9c4df360-50e0-4177-93e7-25c966468180)

## Host environment

Please complete the following information where applicable.

 - Hinode version: `0.27.17`
 - Host OS: `15.3`
 - Node version:`v20.16.0`
 - Browser: `Chrome 132.0.6834.57 (Official Build) beta (arm64)`
## Hugo environment

Copy the output of `hugo env` or `npm run env` here.

```bash
hugo v0.140.1+extended+withdeploy darwin/arm64 BuildDate=2024-12-23T16:26:35Z VendorInfo=brew
GOOS="darwin"
GOARCH="arm64"
GOVERSION="go1.23.4"
github.com/sass/libsass="3.6.6"
github.com/webmproject/libwebp="v1.3.2"
```
