### ISSUE TITLE
Question: change opacity of carousel

### ISSUE THREAD

**Issue by tobythesharpeagle** [gethinode/hinode#287]
Hi, where can I change the opacity of the carousel component so that I don't get any darkness on top of the photos? Thank you!

**Comment by markdumay** [comment]
Adjust the alpha value of `background-color` of the class `gradient` to the following value:

```css
.gradient {
    // background-color: rgba(0, 0, 0, 0.3); // old value
    background-color: rgba(0, 0, 0, 0);  // new value
}
```

When using the Hinode template, simply copy the above statement to `assets/scss/theme/theme.scss`. When using Hinode as fork, simply update the value in `assets/scss/components/_carousel.scss`.
