### ISSUE TITLE
sidebar should support an item that has `link` and `title`

### ISSUE THREAD

**Issue by hustcer** [gethinode/hinode#510]
**Is your feature request related to a problem? Please describe.**
Sidebar should support nav items that has `link` and `title` properties, currently it has only one property `title` and the link was created from the title by `urlize` it. Thats' not enough, especially for non-English docs: For a doc named `说明.md` may generate a link like `/docs/说明/` and the URL is not quit friendly.

**Describe the solution you'd like**
It's better to provide some feature like [Vuepress Sidebar Config](https://vuepress.vuejs.org/theme/default-theme-config.html#sidebar-groups) so we can config it like this:
```yaml
- title: 开始
  link: '/start'
  pages:
    - title: 介绍
      link: '/introduction'
    - title: 安装
      link: '/install'
- title: 关于
  link: '/about'
```

Thanks.
