### ISSUE TITLE
Add Chinese translation

### ISSUE THREAD

**Issue by uvham521** [gethinode/hinode#663]
**Is your feature request related to a problem? Please describe.**

I am a Chinese user. When I set the site language to Chinese, the text in the theme dropdown box becomes blank, only showing icons.

Here are my configuration options. The result is shown in the image below.

```toml
languageCode = "zh_CN"
defaultContentLanguage = "zh_CN"
defaultContentLanguageInSubdir = false
```

![image](https://github.com/gethinode/hinode/assets/28501148/6c7205a4-1386-4f8d-bef8-f1f712dd6eec)

**Describe the solution you'd like**

Add support for the Chinese language. For example, Simplified Chinese(zh_CN) and Traditional Chinese(zh_HK).

**Describe alternatives you've considered**

It seems that there is no simpler way than adding a Chinese translation file.
