### ISSUE TITLE
[BUG] menu items links in navigation bar are incorrect

### ISSUE THREAD

**Issue by vinser** [gethinode/hinode#980]
## Describe the bug
When `baseURL = 'https://user.github.io/subfolder/'` menu items links in navigation bar are incorrect

For example, these are
```
http://localhost:1313/subfolder/subfolder/en/apps/
http://localhost:1313/subfolder/subfolder/en/news/
```
instead of
 ```
http://localhost:1313/subfolder/en/apps/
http://localhost:1313/subfolder/en/news/
```  

If I change line 24 in `site/layouts/partials/assets/navbar-item.html` from
```
24    {{- $menuURL := urls.JoinPath $baseURL ((or $menu.PageRef $menu.URL) | relLangURL) -}}
```
to
```
24    {{- $menuURL := or $menu.PageRef $menu.URL | relLangURL -}}
```
navbar works as expected with or without subfolder in baseURL

## Screenshots
navigation bar
![image](https://github.com/gethinode/hinode/assets/14954512/e9efe70f-32a5-4691-9052-a1919c2c63e5)

## Host environment
 - Hinode version: [e.g. v0.24.0]
 - Host OS: [e.g. Ubuntu 22.04]
 - Node version: -
 - Browser: Brave (arm64)

## Hugo environment
```bash
$ hugo env
hugo v0.126.3-44f1edcb0647cdd6c59ba07530cec156f6622a77+extended linux/arm64 BuildDate=2024-06-02T13:02:43Z VendorInfo=snap:0.126.3
GOOS="linux"
GOARCH="arm64"
GOVERSION="go1.22.3"
github.com/sass/libsass="3.6.5"
github.com/webmproject/libwebp="v1.3.2"
github.com/sass/dart-sass/protocol="2.7.1"
github.com/sass/dart-sass/compiler="1.77.4"
github.com/sass/dart-sass/implementation="1.77.4"
```

**Comment by markdumay** [comment]
To understand the issue a bit better, could you share the configuration of your menu?

Just to double check, the menu items should **not** include the deployment folder. The following example is taken from the example site:

```toml
[[main]]
  name = "Projects"
  pageRef = "/projects/"
  weight = 30

[[main]]
  name = "Sample project"
  pageRef = "/projects/sample-project/"
  parent = "Projects"
  weight = 1
```

**Comment by vinser** [comment]
In `menu.en.tomle` I had
```toml
[[main]]
  name = "Apps"
  pageRef = "apps/"
  weight = 20

[[main]]
  name = "News"
  pageRef = "news/"
  weight = 30
```
I found that pageRef MUST have leading slash "/". With this fix 
```toml
[[main]]
  name = "Apps"
  pageRef = "/apps/"
  weight = 20

[[main]]
  name = "News"
  pageRef = "/news/"
  weight = 30
```
menu items work fine

Thank you!
